In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("numpy_dataset.csv")

In [3]:
df

,Age,Height_cm,Weight_kg,Salary,Experience_years
0,56.0,157.0,74.2,41531.64,23.3
1,46.0,178.8,73.0,34969.30,6.1
2,32.0,179.1,56.6,54196.36,32.0
3,25.0,178.9,64.9,8885.68,14.7
4,38.0,156.2,39.9,43120.71,13.4
...,...,...,...,...,...
195,23.0,175.7,67.5,60763.87,27.9
196,49.0,147.1,89.5,42962.78,23.0
197,21.0,160.5,84.4,57904.06,29.8
198,28.0,177.0,76.2,74308.00,30.4


In [4]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [6]:
df.isnull().sum()

Age                 0
Height_cm           0
Weight_kg           0
Salary              0
Experience_years    0
dtype: int64

In [7]:
# now we sweetly chnage then df to numpy array
x = df.to_numpy()

In [8]:
x

array([[5.600000e+01, 1.570000e+02, 7.420000e+01, 4.153164e+04,
        2.330000e+01],
       [4.600000e+01, 1.788000e+02, 7.300000e+01, 3.496930e+04,
        6.100000e+00],
       [3.200000e+01, 1.791000e+02, 5.660000e+01, 5.419636e+04,
        3.200000e+01],
       [2.500000e+01, 1.789000e+02, 6.490000e+01, 8.885680e+03,
        1.470000e+01],
       [3.800000e+01, 1.562000e+02, 3.990000e+01, 4.312071e+04,
        1.340000e+01],
       [5.600000e+01, 1.658000e+02, 8.620000e+01, 4.539925e+04,
        1.820000e+01],
       [3.600000e+01, 1.601000e+02, 6.130000e+01, 2.713564e+04,
        1.600000e+00],
       [4.000000e+01, 1.742000e+02, 7.460000e+01, 6.196604e+04,
        5.800000e+00],
       [2.800000e+01, 1.821000e+02, 7.240000e+01, 3.291287e+04,
        2.580000e+01],
       [2.800000e+01, 1.737000e+02, 8.130000e+01, 5.401614e+04,
        2.900000e+00],
       [4.100000e+01, 1.651000e+02, 5.980000e+01, 9.175666e+04,
        2.110000e+01],
       [5.300000e+01, 1.613000e+02, 6.74000

In [10]:
x.shape

(200, 5)

In [11]:
x.ndim

2

In [12]:
x.dtype

dtype('float64')

In [13]:
x.size

1000

In [14]:
x[0,1]

np.float64(157.0)

In [15]:
x[2,2]

np.float64(56.6)

In [16]:
x[:,1]

array([157. , 178.8, 179.1, 178.9, 156.2, 165.8, 160.1, 174.2, 182.1,
       173.7, 165.1, 161.3, 171.5, 152.8, 170.4, 155.9, 171.2, 163.4,
       161.1, 156.1, 161.4, 170.6, 175.4, 170.3, 178.6, 190.4, 161.8,
       162.9, 150.6, 176.9, 178. , 156.3, 171.2, 177.2, 167.3, 173.5,
       166.7, 152.8, 175.5, 178.3, 172.3, 155.5, 157.5, 153.7, 172.7,
       177.7, 169.2, 174.4, 156.3, 166.5, 151.3, 157.3, 173.8, 162.6,
       177.1, 170.4, 192.3, 165.9, 150.9, 164.7, 155.4, 174.8, 165.4,
       163.6, 163.8, 172.4, 160.5, 172.8, 175.5, 161.6, 155.7, 159.9,
       172.1, 165.9, 171.3, 182.6, 167.3, 156.9, 175.6, 165.5, 173.7,
       175.7, 155.4, 178.8, 174.1, 159. , 168. , 167.6, 165.2, 173.7,
       179.4, 165.1, 178.3, 174.9, 167.3, 166.8, 153.5, 150. , 166.7,
       156.4, 164.6, 159.7, 147.1, 168.6, 160.9, 165.8, 156.1, 161.7,
       180.6, 166.3, 170.5, 152.3, 188.9, 183.4, 178.6, 173.3, 165.2,
       169.4, 175.5, 158.7, 160.6, 148.3, 157.3, 181.6, 161.7, 161.8,
       168.2, 148.9,

In [17]:
x[1,:]

array([4.60000e+01, 1.78800e+02, 7.30000e+01, 3.49693e+04, 6.10000e+00])

In [21]:
ages = x[:, 0]

In [22]:
ages + 1

array([57., 47., 33., 26., 39., 57., 37., 41., 29., 29., 42., 54., 58.,
       42., 21., 40., 20., 42., 48., 56., 20., 39., 51., 30., 40., 43.,
       45., 60., 46., 34., 33., 21., 55., 25., 39., 27., 57., 36., 22.,
       43., 32., 27., 44., 20., 38., 46., 25., 26., 53., 32., 35., 54.,
       58., 22., 20., 24., 60., 22., 47., 36., 44., 52., 28., 54., 32.,
       49., 33., 26., 32., 41., 58., 39., 34., 36., 42., 44., 43., 59.,
       47., 33., 19., 43., 25., 27., 42., 19., 26., 42., 29., 35., 26.,
       53., 53., 51., 23., 60., 57., 59., 46., 25., 27., 26., 30., 52.,
       51., 41., 42., 55., 53., 58., 40., 45., 53., 19., 53., 55., 32.,
       21., 19., 23., 44., 32., 57., 45., 27., 33., 33., 44., 60., 31.,
       50., 57., 50., 22., 48., 55., 41., 57., 33., 47., 54., 31., 50.,
       25., 40., 46., 20., 60., 24., 46., 46., 38., 48., 29., 46., 43.,
       57., 51., 19., 45., 31., 59., 21., 57., 24., 26., 45., 27., 55.,
       51., 60., 42., 33., 50., 50., 42., 59., 30., 57., 20., 21

In [23]:
ages*ages

array([3136., 2116., 1024.,  625., 1444., 3136., 1296., 1600.,  784.,
        784., 1681., 2809., 3249., 1681.,  400., 1521.,  361., 1681.,
       2209., 3025.,  361., 1444., 2500.,  841., 1521., 1764., 1936.,
       3481., 2025., 1089., 1024.,  400., 2916.,  576., 1444.,  676.,
       3136., 1225.,  441., 1764.,  961.,  676., 1849.,  361., 1369.,
       2025.,  576.,  625., 2704.,  961., 1156., 2809., 3249.,  441.,
        361.,  529., 3481.,  441., 2116., 1225., 1849., 2601.,  729.,
       2809.,  961., 2304., 1024.,  625.,  961., 1600., 3249., 1444.,
       1089., 1225., 1681., 1849., 1764., 3364., 2116., 1024.,  324.,
       1764.,  576.,  676., 1681.,  324.,  625., 1681.,  784., 1156.,
        625., 2704., 2704., 2500.,  484., 3481., 3136., 3364., 2025.,
        576.,  676.,  625.,  841., 2601., 2500., 1600., 1681., 2916.,
       2704., 3249., 1521., 1936., 2704.,  324., 2704., 2916.,  961.,
        400.,  324.,  484., 1849.,  961., 3136., 1936.,  676., 1024.,
       1024., 1849.,

In [26]:
ages / ages

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
ages

array([56., 46., 32., 25., 38., 56., 36., 40., 28., 28., 41., 53., 57.,
       41., 20., 39., 19., 41., 47., 55., 19., 38., 50., 29., 39., 42.,
       44., 59., 45., 33., 32., 20., 54., 24., 38., 26., 56., 35., 21.,
       42., 31., 26., 43., 19., 37., 45., 24., 25., 52., 31., 34., 53.,
       57., 21., 19., 23., 59., 21., 46., 35., 43., 51., 27., 53., 31.,
       48., 32., 25., 31., 40., 57., 38., 33., 35., 41., 43., 42., 58.,
       46., 32., 18., 42., 24., 26., 41., 18., 25., 41., 28., 34., 25.,
       52., 52., 50., 22., 59., 56., 58., 45., 24., 26., 25., 29., 51.,
       50., 40., 41., 54., 52., 57., 39., 44., 52., 18., 52., 54., 31.,
       20., 18., 22., 43., 31., 56., 44., 26., 32., 32., 43., 59., 30.,
       49., 56., 49., 21., 47., 54., 40., 56., 32., 46., 53., 30., 49.,
       24., 39., 45., 19., 59., 23., 45., 45., 37., 47., 28., 45., 42.,
       56., 50., 18., 44., 30., 58., 20., 56., 23., 25., 44., 26., 54.,
       50., 59., 41., 32., 49., 49., 41., 58., 29., 56., 19., 20

In [31]:
experience = x[:,4]

In [32]:
experience

array([23.3,  6.1, 32. , 14.7, 13.4, 18.2,  1.6,  5.8, 25.8,  2.9, 21.1,
        8.6, 13.6, 10.1, 12.4, 25.2, 10.4, 19.8, 16.7, 23.2, 32.8, 25.6,
        7.5,  1.1,  9.2, 20.8,  1.8, 17.4, 20.9, 11.7, 27. ,  3.7,  2.6,
       25.5, 17.3, 24.1, 15.2,  8.6, 28.7, 28. , 24.3,  9.5, 20.7, 12.6,
        3.2, 32.1,  4.8, 33.3, 15.6,  6.5, 19. , 30.6, 25.6, 28.2, 23.1,
       24.2, 29.7,  8.7, 17.1,  7.7, 34.6, 33. ,  1.4, 24.7, 32.4,  6.3,
       19.9, 32. ,  1.2, 24.4, 10.4, 32.4, 34. , 33. , 16.6, 30.2, 29.6,
       11.2, 29. ,  1.3, 20.9,  8.1,  4.2,  2.7, 24.4, 11.9, 25.4,  2.3,
       11. , 18.9, 27.7, 11.2, 21.9, 31. , 21.6,  8.2,  0.9, 30.5,  0.7,
       30.6, 18.5, 32.9, 28. , 34.9, 12.3, 26.9, 14.1, 16.8, 22. , 30.6,
       34.4, 26.9, 14.6, 14.7, 25.8,  8.4,  3.9, 12.4, 10.1, 10.4,  8.2,
        1.5,  0.6, 34.6, 15. , 13.5, 23.8,  7.6, 33.2, 27.5,  3.1, 14.6,
       30.8, 33.1, 16.4, 21.5,  5.8, 34.7,  8.1, 33. , 22.7, 21.3, 17.9,
        8.1,  6.2,  7.7,  6.5, 27.3, 12.3,  2. , 33

In [33]:
salary = x[:, 3]

In [34]:
salary

array([41531.64, 34969.3 , 54196.36,  8885.68, 43120.71, 45399.25,
       27135.64, 61966.04, 32912.87, 54016.14, 91756.66, 25834.92,
       47771.73, 43888.1 , 40970.47, 61403.77, 66594.94, 61574.57,
       39149.91, 86507.72, 23446.35, 34510.56, 52545.94, 51340.91,
       57320.66, 73702.01, 48202.24, 51705.94, 41082.26, 58824.93,
       45222.82, 45214.14, 58152.25, 65523.81, 16878.4 , 55411.68,
       45946.95, 64214.25, 46248.16, 69515.79, 39853.8 , 16545.05,
       65773.9 , 37346.83, 26296.22, 50240.8 , 46412.32, 62346.57,
       63386.16, 51434.31, 36727.76, 54304.12, 52477.92, 58534.05,
       36877.9 , 43994.41, 57640.67, 68709.91, 64488.83, 51230.82,
       42689.07, 56057.31, 33629.14, 37744.98, 72646.57, 56030.52,
       44787.1 , 62437.08, 69304.62, 43330.44, 43588.88, 41710.31,
       64457.75, 64603.36, 70788.55, 65129.04, 25516.73, 54214.46,
       34124.22, 42306.28, 52558.91, 62533.48, 36637.35, 15129.21,
       52707.96, 89653.57, 46957.31, 50703.73, 76732.45, 58854

In [35]:
np.mean(salary)

np.float64(49393.8902)